[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.10"
  FAST_START = "false"
  PYTHONUNBUFFERED = "1"
  NODE_VERSION = "18"

[functions]
  # Configure for heavy ML workloads
  node_bundler = "esbuild"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200