services:
  - type: web
    name: mediai-disease-predictor
    runtime: python
    buildCommand: pip install -r requirements-light.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: FAST_START
        value: "true"
      - key: GUNICORN_CMD_ARGS
        value: "--bind 0.0.0.0:$PORT --timeout 300 --workers 1 --log-level info --access-logfile - --error-logfile -"
    healthCheckPath: /health