services:
  - type: web
    name: mediai-disease-predictor
    runtime: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health